apiVersion: v1
kind: Service
metadata:
  name: pythonhellowroldapp
  namespace: test
spec:
  type: NodePort
  selector:
    app: pythonhellowroldapp
  ports:
  - port: 5000
    targetPort: 5000
    # Optional field
    # Kubernetes control plane will allocate a port from a range (default: 30000-32767).
    # you can also assign a port manually between from a range  (default: 30000-32767)
    nodePort: 30007
